version: "3.3"

services:
    nginx:
      image: nginx
      restart: always
      volumes:
        - .:/var/www/html
        - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      ports:
        - 80:80
      depends_on:
        - php

    php:
        build: .docker
        restart: always
        volumes:
          - .:/var/www/html

    postgres:
      image: postgres:alpine
      restart: always
      environment:
        POSTGRES_PASSWORD: secret
      ports:
        - 5432:5432
      volumes:
        - ./.docker/conf/postgres:/var/lib/postgresql/data/
#         - pgdata:/var/lib/postgresql

# volumes:
#     pgdata:
